sudo: required
services:
    - docker

before_install:
    - docker build -t patrick3dev/vue-travis -f Dockerfile.dev .

script:
    - docker run patrick3dev/vue-travis npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "vue-travis"
    env: "VueTravis-env"
    bucket_name: "elasticbeanstalk-us-east-1-070706141641"
    bucket_path: "vue-travis"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
